### ISSUE TITLE
[Other] Need some help getting started

### ISSUE THREAD

**Issue by Skeeve** [rommapp/romm#1162]
When I first started romm, my directory names were all upper case.

So what I did now was to stop the containers and remove them.I also removed the volumes created and the assets directory, assuming that this will give me a fresh restart.

I then changed all folder names to lower case.

I do not have an IGDB api token as I did not understand how to create one. It seemed to me. as if the instructions are not up to date.

I only have an api key for mobygames.

When starting with `docker-compose up` I get these error messages over and over again:

```
romm       | [2024-09-03 12:55:25 +0000] [21] [INFO] Started server process [21]
romm       | [2024-09-03 12:55:25 +0000] [21] [INFO] Waiting for application startup.
romm       | [2024-09-03 12:55:25 +0000] [21] [INFO] Application startup complete.
romm       | [2024-09-03 12:55:25 +0000] [21] [ERROR] Exception in ASGI application
romm       | Traceback (most recent call last):
romm       |   File "/src/.venv/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
romm       |     result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
romm       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
romm       |     return await self.app(scope, receive, send)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
romm       |     await super().__call__(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
romm       |     await self.middleware_stack(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 151, in __call__
romm       |     await self.app(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 103, in __call__
romm       |     await self.app(scope, receive, send)
romm       |   File "/backend/handler/auth/middleware.py", line 146, in __call__
romm       |     await self.app(scope, receive, send_wrapper)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/authentication.py", line 36, in __call__
romm       |     auth_result = await self.backend.authenticate(conn)
romm       |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/backend/handler/auth/hybrid_auth.py", line 10, in authenticate
romm       |     user = await auth_handler.get_current_active_user_from_session(conn)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/backend/handler/auth/base_handler.py", line 85, in get_current_active_user_from_session
romm       |     raise HTTPException(
romm       | fastapi.exceptions.HTTPException: 403: User not found
romm       | [2024-09-03 12:55:26 +0000] [21] [INFO] connection closed
```

What could be wrong?

**Comment by gantoine** [comment]
Try clearing your cookies, it's trying to send old/bad cookies.

**Comment by Skeeve** [comment]
Thanks! I simply closed the browser tab and the messages were gone.
