### ISSUE TITLE
Illegal header value b'Bearer'

### ISSUE THREAD

**Issue by jaymedavis** [rommapp/romm#1259]
hello!   brand new install via docker.  I am getting this error when clicking 'scan'.  I am trying to upload games for snes (.sfc files), but getting 'platform not found'.  clicking around led me to this, which seems like I could be missing something?

![Screenshot 2024-10-25 221708](https://github.com/user-attachments/assets/b3c3ea60-b60c-4d6f-8126-78d39da1dcfb)

![{AB518ADF-C6EC-4463-B432-E6D8838E8EA4}](https://github.com/user-attachments/assets/fdaa5ee9-cab1-4fa5-8db0-a24a77ceacb8)

**Comment by blounolito** [comment]
Got the same issue.
Fresh install on Docker (TrueNAS), with mounting on local filesystem, remote database.
Tested on **latest**, and **3.6.0-rc.1**, I tried to recreate all tokens.

**Comment by adamantike** [comment]
Do you have access to the Docker logs, for us to investigate further? This issue is commonly associated to an error while trying to refresh the Twitch API token needed for IGDB.

**Comment by jaymedavis** [comment]
Here you go.  I opened the app, refreshed a time or two, then reproduced the error.   

```
Attaching to romm
romm       | INFO:        [RomM][2024-10-27 00:56:56] Connecting to redis in /src/.venv/bin/gunicorn...
romm       | INFO:        [RomM][2024-10-27 00:56:56] Redis connection established in /src/.venv/bin/gunicorn!
romm       | INFO:        [RomM][2024-10-27 00:56:56] Connecting to redis in /src/.venv/bin/gunicorn...
romm       | INFO:        [RomM][2024-10-27 00:56:56] Redis connection established in /src/.venv/bin/gunicorn!
romm       | INFO:        [RomM][2024-10-27 00:56:56] Connecting to redis in worker.py...
romm       | INFO:        [RomM][2024-10-27 00:56:56] Redis connection established in worker.py!
romm       | INFO:        [RomM][2024-10-27 00:56:56] Connecting to redis in worker.py...
romm       | INFO:        [RomM][2024-10-27 00:56:56] Redis connection established in worker.py!
romm       | 00:56:56 Worker rq:worker:70366c1efb7346b49d53512eac66ada3 started with PID 44, version 1.16.2
romm       | 00:56:56 Subscribing to channel rq:pubsub:70366c1efb7346b49d53512eac66ada3
romm       | 00:56:56 *** Listening on high, default, low...
romm       | 00:56:56 Cleaning registries for queue: high
romm       | StartedJobRegistry cleanup: Moving job to FailedJobRegistry (due to AbandonedJobError)
romm       | 00:56:56 Cleaning registries for queue: default
romm       | 00:56:56 Cleaning registries for queue: low
romm       | INFO:        [RomM][2024-10-27 00:56:57] Connecting to redis in watcher.py...
romm       | INFO:        [RomM][2024-10-27 00:56:57] Redis connection established in watcher.py!
romm       | INFO:        [RomM][2024-10-27 00:56:57] Connecting to redis in watcher.py...
romm       | INFO:        [RomM][2024-10-27 00:56:57] Redis connection established in watcher.py!
romm       | INFO:        [RomM][2024-10-27 00:56:57] Connecting to redis in scheduler.py...
romm       | INFO:        [RomM][2024-10-27 00:56:57] Redis connection established in scheduler.py!
romm       | INFO:        [RomM][2024-10-27 00:56:57] Connecting to redis in scheduler.py...
romm       | INFO:        [RomM][2024-10-27 00:56:57] Redis connection established in scheduler.py!
romm       | [2024-10-27 00:56:57 +0000] [23] [INFO] Started server process [23]
romm       | [2024-10-27 00:56:57 +0000] [23] [INFO] Waiting for application startup.
romm       | [2024-10-27 00:56:57 +0000] [22] [INFO] Started server process [22]
romm       | [2024-10-27 00:56:57 +0000] [22] [INFO] Waiting for application startup.
romm       | [2024-10-27 00:56:57 +0000] [23] [INFO] Application startup complete.
romm       | [2024-10-27 00:56:57 +0000] [22] [INFO] Application startup complete.
romm       | INFO:        [RomM][2024-10-27 00:56:57] Watching /romm/library/roms for changes
romm       | INFO:        [RomM][2024-10-27 00:56:57] Starting scheduler
romm       | INFO:        [nginx][2024-10-27 00:57:01]  172.18.0.1 - - "GET / HTTP/1.1" 200 978 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | 172.18.0.1:0 - "GET /api/heartbeat HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:01]  172.18.0.1 - - "GET /api/heartbeat HTTP/1.1" 200 694 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.024 uct="0.000" uht="0.024" urt="0.024"
romm       | 172.18.0.1:0 - "GET /api/users/me HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:02]  172.18.0.1 - - "GET /api/users/me HTTP/1.1" 200 488 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.017 uct="0.000" uht="0.018" urt="0.018"
romm       | 172.18.0.1:0 - "GET /api/platforms HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:02]  172.18.0.1 - - "GET /api/platforms HTTP/1.1" 200 2 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.010 uct="0.000" uht="0.009" urt="0.009"
romm       | 172.18.0.1:0 - "GET /api/stats HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:02]  172.18.0.1 - - "GET /api/stats HTTP/1.1" 200 74 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.020 uct="0.000" uht="0.021" urt="0.021"
romm       | 172.18.0.1:0 - "GET /api/roms?order_by=id&order_dir=desc&limit=15 HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:02]  172.18.0.1 - - "GET /api/roms?order_by=id&order_dir=desc&limit=15 HTTP/1.1" 200 2 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.014 uct="0.000" uht="0.014" urt="0.014"
romm       | 172.18.0.1:0 - "GET /api/config HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:02]  172.18.0.1 - - "GET /api/config HTTP/1.1" 200 329 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.014 uct="0.000" uht="0.013" urt="0.013"
romm       | 172.18.0.1:0 - "GET /api/collections HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:02]  172.18.0.1 - - "GET /api/collections HTTP/1.1" 200 2 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.016 uct="0.000" uht="0.015" urt="0.015"
romm       | 172.18.0.1:0 - "GET /api/users/me HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:57:02]  172.18.0.1 - - "GET /api/users/me HTTP/1.1" 200 488 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.006 uct="0.000" uht="0.005" urt="0.006"
romm       | [2024-10-27 00:57:02 +0000] [22] [INFO] None - "WebSocket /ws/socket.io/?EIO=4&transport=websocket" [accepted]
romm       | [2024-10-27 00:57:02 +0000] [22] [INFO] connection open
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /ws/socket.io/?EIO=4&transport=websocket HTTP/1.1" 101 138 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=60.844 uct="0.000" uht="0.008" urt="60.854"
romm       | [2024-10-27 00:58:03 +0000] [22] [INFO] connection closed
romm       | 172.18.0.1:0 - "GET /api/heartbeat HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/heartbeat HTTP/1.1" 200 694 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.013 uct="0.000" uht="0.013" urt="0.013"
romm       | 172.18.0.1:0 - "GET /api/users/me HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/users/me HTTP/1.1" 200 488 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.007 uct="0.000" uht="0.007" urt="0.007"
romm       | 172.18.0.1:0 - "GET /api/platforms HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/platforms HTTP/1.1" 200 2 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.007 uct="0.000" uht="0.008" urt="0.008"
romm       | 172.18.0.1:0 - "GET /api/stats HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/stats HTTP/1.1" 200 74 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.013 uct="0.000" uht="0.013" urt="0.013"
romm       | 172.18.0.1:0 - "GET /api/roms?order_by=id&order_dir=desc&limit=15 HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/roms?order_by=id&order_dir=desc&limit=15 HTTP/1.1" 200 2 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.007 uct="0.000" uht="0.006" urt="0.006"
romm       | 172.18.0.1:0 - "GET /api/collections HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/collections HTTP/1.1" 200 2 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.007 uct="0.000" uht="0.007" urt="0.007"
romm       | 172.18.0.1:0 - "GET /api/config HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/config HTTP/1.1" 200 329 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.010 uct="0.000" uht="0.009" urt="0.009"
romm       | 172.18.0.1:0 - "GET /api/users/me HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:03]  172.18.0.1 - - "GET /api/users/me HTTP/1.1" 200 488 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.005 uct="0.000" uht="0.005" urt="0.005"
romm       | [2024-10-27 00:58:03 +0000] [22] [INFO] None - "WebSocket /ws/socket.io/?EIO=4&transport=websocket" [accepted]
romm       | [2024-10-27 00:58:03 +0000] [22] [INFO] connection open
romm       | 172.18.0.1:0 - "GET /api/platforms/supported HTTP/1.0" 200
romm       | INFO:        [nginx][2024-10-27 00:58:09]  172.18.0.1 - - "GET /api/platforms/supported HTTP/1.1" 200 5197 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.015 uct="0.000" uht="0.015" urt="0.015"
romm       | INFO:        [nginx][2024-10-27 00:58:11]  172.18.0.1 - - "GET /assets/platforms/undefined.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:11]  172.18.0.1 - - "GET /assets/platforms/amazon-fire-tv.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:11]  172.18.0.1 - - "GET /assets/platforms/airconsole.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:11]  172.18.0.1 - - "GET /assets/platforms/acorn-archimedes.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:11]  172.18.0.1 - - "GET /assets/platforms/acorn-electron.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:11]  172.18.0.1 - - "GET /assets/platforms/1292-advanced-programmable-video-system.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:12]  172.18.0.1 - - "GET /assets/platforms/undefined.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:12]  172.18.0.1 - - "GET /assets/platforms/undefined.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:12]  172.18.0.1 - - "GET /assets/platforms/visual-memory-unit-slash-visual-memory-system.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:12]  172.18.0.1 - - "GET /assets/platforms/undefined.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [nginx][2024-10-27 00:58:15]  172.18.0.1 - - "GET /assets/platforms/undefined.ico HTTP/1.1" 404 555 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.000 uct="-" uht="-" urt="-"
romm       | INFO:        [RomM][2024-10-27 00:58:54] Detected platform: snes
romm       | INFO:        [RomM][2024-10-27 00:58:54] · snes
romm       | WARNING:  [RomM][2024-10-27 00:58:54] Twitch token invalid: fetching a new one...
romm       | 172.18.0.1:0 - "POST /api/platforms HTTP/1.0" 500
romm       | INFO:        [nginx][2024-10-27 00:58:54]  172.18.0.1 - - "POST /api/platforms HTTP/1.1" 500 21 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.546 uct="0.000" uht="0.546" urt="0.546"
romm       | [2024-10-27 00:58:54 +0000] [22] [ERROR] Exception in ASGI application
romm       | Traceback (most recent call last):
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
romm       |     yield
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
romm       |     resp = await self._pool.handle_async_request(req)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
romm       |     raise exc from None
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
romm       |     response = await connection.handle_async_request(
romm       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
romm       |     return await self._connection.handle_async_request(request)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
romm       |     raise exc
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 93, in handle_async_request
romm       |     await self._send_request_headers(**kwargs)
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpcore/_async/http11.py", line 151, in _send_request_headers
romm       |     with map_exceptions({h11.LocalProtocolError: LocalProtocolError}):
romm       |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
romm       |     self.gen.throw(value)
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
romm       |     raise to_exc(exc) from exc
romm       | httpcore.LocalProtocolError: Illegal header value b'Bearer '
romm       |
romm       | The above exception was the direct cause of the following exception:
romm       |
romm       | Traceback (most recent call last):
romm       |   File "/src/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
romm       |     result = await app(  # type: ignore[func-returns-value]
romm       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
romm       |     return await self.app(scope, receive, send)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
romm       |     await super().__call__(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
romm       |     await self.middleware_stack(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
romm       |     raise exc
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
romm       |     await self.app(scope, receive, _send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
romm       |     with collapse_excgroups():
romm       |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
romm       |     self.gen.throw(value)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
romm       |     raise exc
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
romm       |     response = await self.dispatch_func(request, call_next)
romm       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/backend/utils/context.py", line 41, in set_context_middleware
romm       |     return await call_next(request)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
romm       |     raise app_exc
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
romm       |     await self.app(scope, receive_or_disconnect, send_no_error)
romm       |   File "/backend/handler/auth/middleware.py", line 146, in __call__
romm       |     await self.app(scope, receive, send_wrapper)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/authentication.py", line 48, in __call__
romm       |     await self.app(scope, receive, send)
romm       |   File "/backend/handler/auth/middleware.py", line 19, in __call__
romm       |     await super().__call__(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette_csrf/middleware.py", line 72, in __call__
romm       |     await self.app(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 91, in __call__
romm       |     await self.simple_response(scope, receive, send, request_headers=headers)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 146, in simple_response
romm       |     await self.app(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
romm       |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
romm       |     raise exc
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
romm       |     await app(scope, receive, sender)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
romm       |     await self.middleware_stack(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
romm       |     await route.handle(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
romm       |     await self.app(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
romm       |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
romm       |     raise exc
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
romm       |     await app(scope, receive, sender)
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
romm       |     response = await func(request)
romm       |                ^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
romm       |     raw_response = await run_endpoint_function(
romm       |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
romm       |     return await dependant.call(**values)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/starlette/authentication.py", line 84, in async_wrapper
romm       |     return await func(*args, **kwargs)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/backend/endpoints/platform.py", line 37, in add_platforms
romm       |     scanned_platform = await scan_platform(fs_slug, [fs_slug])
romm       |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/backend/handler/scan_handler.py", line 92, in scan_platform
romm       |     (await meta_igdb_handler.get_platform(platform_attrs["slug"]))
romm       |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/backend/handler/metadata/igdb_handler.py", line 201, in wrapper
romm       |     return await func(*args)
romm       |            ^^^^^^^^^^^^^^^^^
romm       |   File "/backend/handler/metadata/igdb_handler.py", line 308, in get_platform
romm       |     platforms = await self._request(
romm       |                 ^^^^^^^^^^^^^^^^^^^^
romm       |   File "/backend/handler/metadata/igdb_handler.py", line 209, in _request
romm       |     res = await httpx_client.post(
romm       |           ^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1892, in post
romm       |     return await self.request(
romm       |            ^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
romm       |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
romm       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
romm       |     response = await self._send_handling_auth(
romm       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
romm       |     response = await self._send_handling_redirects(
romm       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
romm       |     response = await self._send_single_request(request)
romm       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
romm       |     response = await transport.handle_async_request(request)
romm       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
romm       |     with map_httpcore_exceptions():
romm       |   File "/usr/lib/python3.12/contextlib.py", line 158, in __exit__
romm       |     self.gen.throw(value)
romm       |   File "/src/.venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
romm       |     raise mapped_exc(message) from exc
romm       | httpx.LocalProtocolError: Illegal header value b'Bearer '
romm       | 172.18.0.1:0 - "POST /api/roms HTTP/1.0" 400
romm       | INFO:        [nginx][2024-10-27 00:58:54]  172.18.0.1 - - "POST /api/roms HTTP/1.1" 400 31 "http://localhost/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36" rt=0.067 uct="0.000" uht="0.012" urt="0.013"
```

**Comment by jaymedavis** [comment]
cheers @adamantike!

that was it.  i regenerated my twitch token and its fixed.
