### ISSUE TITLE
[Bug] Error in log after changing user

### ISSUE THREAD

**Issue by nodiaque** [rommapp/romm#1306]
Hello,

I just tried starting my docker with --user-99:100 which are unraid user/group. The docker start fine (I did chmod and chown everything before) but when I trigger the jobs, I'm getting these error:

 ```
INFO:     [RomM][2024-11-17 18:00:37] Connecting to redis in scheduler.py...
INFO:     [RomM][2024-11-17 18:00:37] Redis connection established in scheduler.py!
INFO:     [RomM][2024-11-17 18:00:38] Starting scheduler
Traceback (most recent call last):
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 1364, in _execute_transaction
    response = self.parse_response(connection, "_")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 1432, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ExecAbortError: Transaction discarded because of previous errors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/backend/scheduler.py", line 14, in <module>
    tasks_scheduler.run()
  File "/src/.venv/lib/python3.12/site-packages/rq_scheduler/scheduler.py", line 468, in run
    self.register_birth()
  File "/src/.venv/lib/python3.12/site-packages/rq_scheduler/scheduler.py", line 76, in register_birth
    p.execute()
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 1500, in execute
    return conn.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 1501, in <lambda>
    lambda: execute(conn, stack, raise_on_error),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 1367, in _execute_transaction
    raise errors[0][1]
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 1357, in _execute_transaction
    self.parse_response(connection, "_")
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 1432, in parse_response
    result = Redis.parse_response(self, connection, command_name, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/client.py", line 562, in parse_response
    response = connection.read_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/src/.venv/lib/python3.12/site-packages/redis/connection.py", line 536, in read_response
    raise response
redis.exceptions.ResponseError: Command # 1 (DEL rq:scheduler_instance:fd63bfbc0c184391ad3ea8dc1eab7b3e) of pipeline caused error: MISCONF Redis is configured to save RDB snapshots, but it's currently unable to persist to disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
```

**Comment by gantoine** [comment]
Yeah changing `user` like this tends to break stuff. In your case you'll want to delete the volume you use for redis (whether you use the internal one or not) and start romm up again.

**Comment by nodiaque** [comment]
Ahhhh, I didn't even think it was using it's own redis (just saw there's no redis information in the template, was obvious...).

I'm looking at my map drive and I don't see anything related to redis. All I have is a config file, asset which contains image for the roms and the roms folder.

**Comment by nodiaque** [comment]
ok I found out the docker template I'm using doesn't map it. I just mapped it and now it's fine. Although I triggered to scan everything and it just did titledb, while all 3 task are enabled. I've added a bunch of console and roms and it doesn't detect it

**Comment by gantoine** [comment]
You can open another issue for that, or a support thread in the discord.
