### ISSUE TITLE
[Bug] RomM v3.0.1: "Duplicate column name 'p_name'" on start-up

### ISSUE THREAD

**Issue by zodac** [rommapp/romm#704]
**RomM version**
3.0.1

**Describe the bug**
I'm attempting a clean install of RomM v3.0.1 on docker, but run into issues when starting up. The RomM container has the following error:

```
INFO:     [RomM][alembic.runtime.migration] Context impl MariaDBImpl.
INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.7.1 -> 1.8, update to 1.8
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/backend/lib/python3.10/site-packages/mariadb/cursors.py", line 311, in execute
    self._readresponse()
mariadb.OperationalError: Duplicate column name 'p_name'
```

**To Reproduce**
I've set up my docker-compose.yml similar to the examples:

```
  romm:
    image: zurdi15/romm:3.0.1
    container_name: romm
    hostname: romm
    environment:
      # Database config
      ROMM_DB_DRIVER: "mariadb"
      DB_HOST: "romm-db"
      DB_NAME: "romm-db"
      DB_USER: "romm-user"
      DB_ROOT_PASSWD: "mysqlrootpassword"
      DB_PASSWD: "mysqlpassword"
      # External systems config
      IGDB_CLIENT_ID: "${TWITCH_CLIENT_ID}"
      IGDB_CLIENT_SECRET: "${TWITCH_CLIENT_SECRET}"
      STEAMGRIDDB_API_KEY: "${STEAMGRIDDB_API_KEY}"
      # Authentication config
      ROMM_AUTH_SECRET_KEY: "${ROMM_SECRET_KEY}"
      ROMM_AUTH_USERNAME: "${ADMIN_USERNAME}"
      ROMM_AUTH_PASSWORD: "${ROMM_ADMIN_PASSWORD}"
    ports:
      - "8080:8080"
    restart: "unless-stopped"
    volumes:
      - "${ROMS_DIRECTORY}:/romm/library:ro"
      - "${ROM_SAVES_DIRECTORY}:/romm/assets"
      - "./docker/romm/config/:/romm/config"
      - ./storage/romm/redis/:/redis-data
      - ./storage/romm/resources/:/romm/resources
      - ./storage/romm/logs:/romm/logs

  romm-db:
    image: mariadb:latest
    container_name: romm-db
    hostname: romm-db
    environment:
      MYSQL_ROOT_PASSWORD: "mysqlrootpassword"
      MYSQL_DATABASE: "romm-db"
      MYSQL_USER: "romm-user"
      MYSQL_PASSWORD: "mysqlpassword"
    restart: unless-stopped
    volumes:
      - ./storage/romm-db/:/var/lib/mysql
```

I have cleared any previous storage/volume mounts, so I'm not sure why an upgrade is being performed on the first run.
RomM does not come online, and I can only see the above DB error in the logs.

**Expected behavior**
RomM is able to come online successfully.

**Additional context**
I am running docker on Windows 10. All was working fine previously with RomV v2.3.1 using the sqlite DB.

**Comment by gantoine** [comment]
If you remove everything under `./storage/romm-db` and start again, does it still fail?

**Comment by zodac** [comment]
Yes, I still get the same error. Same if I delete `./storage/romm` only, and restart, or when I delete both.

**Comment by gantoine** [comment]
> [RomM][alembic.runtime.migration] Running upgrade 1.7.1 -> 1.8, update to 1.8

This tells me it's using a database somewhere which is currently on 1.7.1. Are you deleting the `romm-db` container between attempts?

**Comment by zodac** [comment]
Yes, I tried to wipe everything between attempts, so I delete both the `romm` and the `romm-db` containers and remove the storage mounts.

**Comment by zodac** [comment]
Would there be some way to override what version of the DB RomM thinks it's using, or even skip the migration altogether?

**Comment by gantoine** [comment]
Are you comfortable connecting to your DB with a tool like dbeaver, or the mariadb cli?

**Comment by zodac** [comment]
Yeah, that shouldn't be a problem, any commands you want me to try?

**Comment by gantoine** [comment]
Ok so you have 3 options here:

a) `exec sh` into the romm container, edit `/backend/alembic/versions/1.8_.py` and under the `upgrade` function (the migration), comment out the block `with op.batch_alter_table("platforms") as batch_op:` and the line `batch_op.add_column(sa.Column("p_name", sa.String(length=150), nullable=True))`. run migrations, then after the next failure go back in and comment out up to the next line that fails, then keep doing that till the migration completes

b) open the `roms` table in maraidb, delete the `p_name` column, then run the migration. when it fails next do the same thing with whichever column is now a duplicate

c) on maraidb, skip the entire migration by changing the value in `alembic_version` table to `1.8.1` (though this will break things of the entire migration didnt run the last time)

**Comment by Silver-Rabbit** [comment]
Had the same problem with a clean installation using the latest docker image.
Solved it by commenting out the individual lines in the migration scripts:
- /backend/alembic/versions/1.8_.py
- /backend/alembic/versions/0014_asset_files.py

I attached the modified migration scripts.
[migration_scripts.zip](https://github.com/zurdi15/romm/files/14627914/migration_scripts.zip)

Maybe they help to find the bug in the migration.

**Comment by zodac** [comment]
No, not having any joy I'm afraid.

1) Each of the upgrade functions was causing problems, so I had to skip them all, but then I just got a `Got error 42 "No message of desired type" from storage engine InnoDB` error.

2) I attempted this but kept running into more and more issues. While I was able to slowly work through each one, I eventually ran into a `Tablespace is missing for a table` error.

3) I also got a `Tablespace is missing for a table` error when setting the version to 1.8.1.

4) I attempted to use the scripts provided by @Silver-Rabbit , but getting the same tablespace error as above.

I'm not sure why a migration is even necessary - is it not possible to use the latest schema if doing a fresh install?

**Comment by gantoine** [comment]
@zodac If you wipe your DB, delete any SQLite database you have mounted, and start fresh, it should work. Obviously it means loosing any manual linking of games with IGDB, so it's really a last resort type of thing.

FWIW I've done it 4 times so far on my 2K+ collection of games, due to bad migrations in past beta versions!

**Comment by zodac** [comment]
I was deleting the volumes for both mariadb and romm (all listed in the OP), though I wasn't running any SQL commands to drop tables/delete DBs first. Are there any other things I need to wipe? I thought there was no SQLite for v3?

**Comment by gantoine** [comment]
Did you do it in this order: stop mariadb container, rm mariadb, rm the volume, then start mariadb again?

**Comment by zodac** [comment]
Yes, that order, but I do both mariadb and romm.

**Comment by gantoine** [comment]
Can you post the romm logs when it starts up again?

**Comment by zodac** [comment]
Sure. I did the following process:
- Stopped both containers
- Removed both containers
- Removed both containers' volumes
- Started the containers again

Attached the log from RomM: [romm.log](https://github.com/rommapp/romm/files/14681275/romm.log)

**Comment by zodac** [comment]
I had posted it in the OP. I've also tried with names volumes (a `volumes:` block in my docker-compose), but that's having the same problem. I also rm'd any extra docker volumes in case one was created by the Dockerfile that I had missed,

**Comment by zodac** [comment]
Hey, just an update. I ended up reinstalling Docker from scratch, cleaning out everything. I was able to get it working afterwards with v3.1.0-rc.1. Going to wait for v3.1.0 final, then will test fully. :)

Happy to close this one off though.

**Comment by taschmidt** [comment]
This is definitely still broken. Trying with a brand new install and getting errors on the migration scripts. Definitely doesn't seem like defensive coding.

**Comment by gantoine** [comment]
> Definitely doesn't seem like defensive coding.

Sure thing mister 2 commits in the last 12 months.

**Comment by taschmidt** [comment]
> > Definitely doesn't seem like defensive coding.
> 
> Sure thing mister 2 commits in the last 12 months.

Wow, what a stupid comment.

**Comment by PSFW** [comment]
Unfortunately I have also not been able to get the migration scripts to work from a clean install. I have tried with multiple versions of the romm image, cleaning down my docker volumes each time (for both romm and the database). Is there a way of running the docker image without the migration scripts that I may be missing?

**Comment by PSFW** [comment]
With a fresh install of `rommapp/romm:3.9.0`, I have the following logs:
2025-05-29 08:01:06 INFO:     [RomM][alembic.runtime.migration] Context impl MariaDBImpl.
2025-05-29 08:01:06 INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
2025-05-29 08:01:07 INFO:     [RomM][alembic.runtime.migration] Running upgrade  -> 1.6.2, init to 1.6.2
2025-05-29 08:01:07 INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.6.2 -> 1.6.3, update to 1.6.3
2025-05-29 08:01:07 INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.6.3 -> 1.7.1, update to 1.7.1
2025-05-29 08:01:08 INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.7.1 -> 1.8, update to 1.8
2025-05-29 08:01:08 Traceback (most recent call last):
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2025-05-29 08:01:08     self.dialect.do_execute(
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
2025-05-29 08:01:08     cursor.execute(statement, parameters)
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/mariadb/cursors.py", line 310, in execute
2025-05-29 08:01:08     self._readresponse()
2025-05-29 08:01:08 mariadb.OperationalError: Error on rename of './romm/roms' to './romm/old_roms' (errno: 194 "Tablespace is missing for a table")
2025-05-29 08:01:08 
2025-05-29 08:01:08 The above exception was the direct cause of the following exception:
2025-05-29 08:01:08 
2025-05-29 08:01:08 Traceback (most recent call last):
2025-05-29 08:01:08   File "/src/.venv/bin/alembic", line 8, in <module>
2025-05-29 08:01:08     sys.exit(main())
2025-05-29 08:01:08              ^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 641, in main
2025-05-29 08:01:08     CommandLine(prog=prog).main(argv=argv)
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 631, in main
2025-05-29 08:01:08     self.run_cmd(cfg, options)
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 608, in run_cmd
2025-05-29 08:01:08     fn(
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/command.py", line 403, in upgrade
2025-05-29 08:01:08     script.run_env()
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
2025-05-29 08:01:08     util.load_python_file(self.dir, "env.py")
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
2025-05-29 08:01:08     module = load_module_py(module_id, path)
2025-05-29 08:01:08              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
2025-05-29 08:01:08     spec.loader.exec_module(module)  # type: ignore
2025-05-29 08:01:08     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
2025-05-29 08:01:08   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-05-29 08:01:08   File "/backend/alembic/env.py", line 102, in <module>
2025-05-29 08:01:08     run_migrations_online()
2025-05-29 08:01:08   File "/backend/alembic/env.py", line 96, in run_migrations_online
2025-05-29 08:01:08     context.run_migrations()
2025-05-29 08:01:08   File "<string>", line 8, in run_migrations
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
2025-05-29 08:01:08     self.get_context().run_migrations(**kw)
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
2025-05-29 08:01:08     step.migration_fn(**kw)
2025-05-29 08:01:08   File "/backend/alembic/versions/1.8_.py", line 58, in upgrade
2025-05-29 08:01:08     batch_op.execute("ALTER TABLE roms RENAME TO old_roms")
2025-05-29 08:01:08   File "<string>", line 3, in execute
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/operations/ops.py", line 2554, in batch_execute
2025-05-29 08:01:08     return cls.execute(
2025-05-29 08:01:08            ^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/operations/ops.py", line 2537, in execute
2025-05-29 08:01:08     return operations.invoke(op)
2025-05-29 08:01:08            ^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/operations/base.py", line 445, in invoke
2025-05-29 08:01:08     return fn(self, operation)
2025-05-29 08:01:08            ^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/operations/toimpl.py", line 224, in execute_sql
2025-05-29 08:01:08     operations.migration_context.impl.execute(
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/ddl/impl.py", line 214, in execute
2025-05-29 08:01:08     self._exec(sql, execution_options)
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/alembic/ddl/impl.py", line 207, in _exec
2025-05-29 08:01:08     return conn.execute(construct, multiparams)
2025-05-29 08:01:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
2025-05-29 08:01:08     return meth(
2025-05-29 08:01:08            ^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
2025-05-29 08:01:08     return connection._execute_clauseelement(
2025-05-29 08:01:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1638, in _execute_clauseelement
2025-05-29 08:01:08     ret = self._execute_context(
2025-05-29 08:01:08           ^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
2025-05-29 08:01:08     return self._exec_single_context(
2025-05-29 08:01:08            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
2025-05-29 08:01:08     self._handle_dbapi_exception(
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
2025-05-29 08:01:08     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2025-05-29 08:01:08     self.dialect.do_execute(
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
2025-05-29 08:01:08     cursor.execute(statement, parameters)
2025-05-29 08:01:08   File "/src/.venv/lib/python3.12/site-packages/mariadb/cursors.py", line 310, in execute
2025-05-29 08:01:08     self._readresponse()
2025-05-29 08:01:08 sqlalchemy.exc.OperationalError: (mariadb.OperationalError) Error on rename of './romm/roms' to './romm/old_roms' (errno: 194 "Tablespace is missing for a table")
2025-05-29 08:01:08 [SQL: ALTER TABLE roms RENAME TO old_roms]
2025-05-29 08:01:08 (Background on this error at: https://sqlalche.me/e/20/e3q8)
2025-05-29 08:01:13 INFO:     [RomM][alembic.runtime.migration] Context impl MariaDBImpl.
2025-05-29 08:01:13 INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
2025-05-29 08:01:13 INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.7.1 -> 1.8, update to 1.8
2025-05-29 08:01:13 Traceback (most recent call last):
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2025-05-29 08:01:13     self.dialect.do_execute(
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
2025-05-29 08:01:13     cursor.execute(statement, parameters)
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/mariadb/cursors.py", line 310, in execute
2025-05-29 08:01:13     self._readresponse()
2025-05-29 08:01:13 mariadb.OperationalError: Duplicate column name 'p_name'
2025-05-29 08:01:13 
2025-05-29 08:01:13 The above exception was the direct cause of the following exception:
2025-05-29 08:01:13 
2025-05-29 08:01:13 Traceback (most recent call last):
2025-05-29 08:01:13   File "/src/.venv/bin/alembic", line 8, in <module>
2025-05-29 08:01:13     sys.exit(main())
2025-05-29 08:01:13              ^^^^^^
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 641, in main
2025-05-29 08:01:13     CommandLine(prog=prog).main(argv=argv)
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 631, in main
2025-05-29 08:01:13     self.run_cmd(cfg, options)
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/config.py", line 608, in run_cmd
2025-05-29 08:01:13     fn(
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/command.py", line 403, in upgrade
2025-05-29 08:01:13     script.run_env()
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
2025-05-29 08:01:13     util.load_python_file(self.dir, "env.py")
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
2025-05-29 08:01:13     module = load_module_py(module_id, path)
2025-05-29 08:01:13              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
2025-05-29 08:01:13     spec.loader.exec_module(module)  # type: ignore
2025-05-29 08:01:13     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:13   File "<frozen importlib._bootstrap_external>", line 999, in exec_module
2025-05-29 08:01:13   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
2025-05-29 08:01:13   File "/backend/alembic/env.py", line 102, in <module>
2025-05-29 08:01:13     run_migrations_online()
2025-05-29 08:01:13   File "/backend/alembic/env.py", line 96, in run_migrations_online
2025-05-29 08:01:13     context.run_migrations()
2025-05-29 08:01:13   File "<string>", line 8, in run_migrations
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
2025-05-29 08:01:13     self.get_context().run_migrations(**kw)
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
2025-05-29 08:01:13     step.migration_fn(**kw)
2025-05-29 08:01:13   File "/backend/alembic/versions/1.8_.py", line 42, in upgrade
2025-05-29 08:01:13     with op.batch_alter_table("roms") as batch_op:
2025-05-29 08:01:13          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:13   File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
2025-05-29 08:01:13     next(self.gen)
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/operations/base.py", line 398, in batch_alter_table
2025-05-29 08:01:13     impl.flush()
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/operations/batch.py", line 116, in flush
2025-05-29 08:01:13     fn(*arg, **kw)
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/ddl/impl.py", line 334, in add_column
2025-05-29 08:01:13     self._exec(base.AddColumn(table_name, column, schema=schema))
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/alembic/ddl/impl.py", line 207, in _exec
2025-05-29 08:01:13     return conn.execute(construct, multiparams)
2025-05-29 08:01:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
2025-05-29 08:01:13     return meth(
2025-05-29 08:01:13            ^^^^^
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/sql/ddl.py", line 180, in _execute_on_connection
2025-05-29 08:01:13     return connection._execute_ddl(
2025-05-29 08:01:13            ^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1527, in _execute_ddl
2025-05-29 08:01:13     ret = self._execute_context(
2025-05-29 08:01:13           ^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1843, in _execute_context
2025-05-29 08:01:13     return self._exec_single_context(
2025-05-29 08:01:13            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
2025-05-29 08:01:13     self._handle_dbapi_exception(
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2352, in _handle_dbapi_exception
2025-05-29 08:01:13     raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
2025-05-29 08:01:13     self.dialect.do_execute(
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 942, in do_execute
2025-05-29 08:01:13     cursor.execute(statement, parameters)
2025-05-29 08:01:13   File "/src/.venv/lib/python3.12/site-packages/mariadb/cursors.py", line 310, in execute
2025-05-29 08:01:13     self._readresponse()
2025-05-29 08:01:13 sqlalchemy.exc.OperationalError: (mariadb.OperationalError) Duplicate column name 'p_name'
2025-05-29 08:01:13 [SQL: ALTER TABLE roms ADD COLUMN p_name VARCHAR(150)]
2025-05-29 08:01:13 (Background on this error at: https://sqlalche.me/e/20/e3q8)

**Comment by gantoine** [comment]
@PSFW are you dropping the mariadb container and volume `$ROMM_DB_CONFIG_DIR` between changes? you can't just change the romm image with an existing database if you want to start from scratch.
