### ISSUE TITLE
[Bug] DB Error when migrating to 3.0

### ISSUE THREAD

**Issue by Djiit** [rommapp/romm#752]
**RomM version**
3.0.1

**Describe the bug**

When running the official image on an existing sqlite DB (or, at least, that's the only diff I see versus a whole new DB), it breaks with this message.

I droppped the DB, created a new one and granted rights to my users and retried everything, same thing:

```
stream logs failed container "main" in pod "romm-7b86494b9b-96x5f" is waiting to start: ContainerCreating for romm/romm-7b86494b9b-96x5f (main)
stream logs failed container "main" in pod "romm-7b86494b9b-96x5f" is waiting to start: ContainerCreating for romm/romm-7b86494b9b-96x5f (main)
stream logs failed container "main" in pod "romm-7b86494b9b-96x5f" is waiting to start: ContainerCreating for romm/romm-7b86494b9b-96x5f (main)
stream logs failed container "main" in pod "romm-7b86494b9b-96x5f" is waiting to start: ContainerCreating for romm/romm-7b86494b9b-96x5f (main)
INFO:     [init][2024-03-25 08:42:53] starting redis-server
8:C 25 Mar 2024 08:42:53.436 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
8:C 25 Mar 2024 08:42:53.437 * Redis version=7.2.4, bits=64, commit=00000000, modified=0, pid=8, just started
8:C 25 Mar 2024 08:42:53.437 * Configuration loaded
8:M 25 Mar 2024 08:42:53.438 * monotonic clock: POSIX clock_gettime
8:M 25 Mar 2024 08:42:53.450 * Running mode=standalone, port=6379.
8:M 25 Mar 2024 08:42:53.451 * Server initialized
8:M 25 Mar 2024 08:42:53.451 * Ready to accept connections tcp
INFO:     [RomM][alembic.runtime.migration] Context impl MariaDBImpl.
INFO:     [RomM][alembic.runtime.migration] Will assume non-transactional DDL.
INFO:     [RomM][alembic.runtime.migration] Running upgrade  -> 1.6.2, init to 1.6.2
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.6.2 -> 1.6.3, update to 1.6.3
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.6.3 -> 1.7.1, update to 1.7.1
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.7.1 -> 1.8, update to 1.8
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.8 -> 1.8.1, update to 1.8.1
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.8.1 -> 1.8.2, update to 1.8.2
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.8.2 -> 1.8.3, update to 1.8.3
INFO:     [RomM][alembic.runtime.migration] Running upgrade 1.8.3 -> 2.0.0, update to 2.0.0
INFO:     [RomM][alembic.runtime.migration] Running upgrade 2.0.0 -> 0009_models_refactor, empty message
INFO:     [RomM][alembic.runtime.migration] Running upgrade 0009_models_refactor -> 0010_igdb_id_integerr, empty message
INFO:     [RomM][alembic.runtime.migration] Running upgrade 0010_igdb_id_integerr -> 0011_drop_has_cover, empty message
INFO:     [RomM][alembic.runtime.migration] Running upgrade 0011_drop_has_cover -> 0012_add_regions_languages, empty message
INFO:     [RomM][alembic.runtime.migration] Running upgrade 0012_add_regions_languages -> 0013_upgrade_file_extension, empty message
INFO:     [RomM][alembic.runtime.migration] Running upgrade 0013_upgrade_file_extension -> 0014_asset_files, empty message
Traceback (most recent call last):
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/backend/lib/python3.10/site-packages/mariadb/cursors.py", line 311, in execute
    self._readresponse()
mariadb.IntegrityError: Cannot add or update a child row: a foreign key constraint fails (`romm`.`#sql-alter-1-1daf`, CONSTRAINT `fk_platform_id_roms` FOREIGN KEY (`platform_id`) REFERENCES `platforms` (`id`) ON DELETE CASCADE)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/bin/alembic", line 8, in <module>
    sys.exit(main())
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 591, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 585, in main
    self.run_cmd(cfg, options)
  File "/backend/lib/python3.10/site-packages/alembic/config.py", line 562, in run_cmd
    fn(
  File "/backend/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/backend/lib/python3.10/site-packages/alembic/script/base.py", line 576, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/backend/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/backend/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/backend/alembic/env.py", line 86, in <module>
    run_migrations_online()
  File "/backend/alembic/env.py", line 80, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/backend/lib/python3.10/site-packages/alembic/runtime/environment.py", line 868, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/backend/lib/python3.10/site-packages/alembic/runtime/migration.py", line 622, in run_migrations
    step.migration_fn(**kw)
  File "/backend/alembic/versions/0014_asset_files.py", line 206, in upgrade
    with op.batch_alter_table("roms", schema=None) as batch_op:
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/backend/lib/python3.10/site-packages/alembic/operations/base.py", line 383, in batch_alter_table
    impl.flush()
  File "/backend/lib/python3.10/site-packages/alembic/operations/batch.py", line 113, in flush
    fn(*arg, **kw)
  File "/backend/lib/python3.10/site-packages/alembic/ddl/impl.py", line 335, in add_constraint
    self._exec(schema.AddConstraint(const))
  File "/backend/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1528, in _execute_ddl
    ret = self._execute_context(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2344, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/backend/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/backend/lib/python3.10/site-packages/mariadb/cursors.py", line 311, in execute
    self._readresponse()
sqlalchemy.exc.IntegrityError: (mariadb.IntegrityError) Cannot add or update a child row: a foreign key constraint fails (`romm`.`#sql-alter-1-1daf`, CONSTRAINT `fk_platform_id_roms` FOREIGN KEY (`platform_id`) REFERENCES `platforms` (`id`) ON DELETE CASCADE)
[SQL: ALTER TABLE roms ADD CONSTRAINT fk_platform_id_roms FOREIGN KEY(platform_id) REFERENCES platforms (id) ON DELETE CASCADE]
(Background on this error at: https://sqlalche.me/e/20/gkpj)
ERROR:    [init][2024-03-25 08:46:28] Something went horribly wrong with our database
Stream closed EOF for romm/romm-7b86494b9b-96x5f (main)
```

**To Reproduce**
- Run 3.0.1 image with an existing 2.X sqlite database.

**Expected behavior**
It works :]

**Comment by gantoine** [comment]
We've seen a number of these in the sqlite to maria transition, I'd recommend starting from scratch when 3.1 drops in a few days.

**Comment by Djiit** [comment]
That's really a bummer. Those breaking changes are really killing the product. Same for the decision to include Redis in the image.
Thanks for your work anyway.

**Comment by gantoine** [comment]
>  Those breaking changes are really killing the product

If I could guarantee 0 migration issues and data loss, I'd be charging for the product ;)

> Same for the decision to include Redis in the image

In 3.1 we're bringing back the option to run Redis externally; passing a host and port will stop the built-in Redis from running.
