### ISSUE TITLE
[Bug] Complete Rescan Not Detecting Removed Platforms

### ISSUE THREAD

**Issue by jcsomerville** [rommapp/romm#852]
**RomM version**
3.2.0-rc.1

**Describe the bug**
I removed maybe half my library from my hard drive and when I initiated a Complete Rescan the files that remained were correctly identified   but RomM did not detect missing files and remove them from the library.

**To Reproduce**
1. Remove 1 or more game from hard drive/RomM file structure.
2. Initiate a Complete Rescan
3. When completed check library and see that the removed games from disk are still present in RomM

**Expected behavior**
Games removed form disk should also be detected by RomM and also be removed from library/database.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 TLS
 - Browser: Tested on Chrome, Brave and Firefox

**Additional context**
I don't think this is important but maybe it should be noted that I formated the drive that the games/folder structure RomM was "looking" at.

After formatting I copied some of the games back to the same location and file structure as had been established before the formatting.

**Comment by gantoine** [comment]
That's odd, I just tested this locally and on my server and in both cases it was removed. I tested both a quick scan and complete rescan, works in both cases. Looking at the code nothing was changed around purging games no longer in

>  It should be noted that I formatted the drive that the games/folder structure RomM was "looking" at

At first glance I don't see how this could be related, but maybe it is causing some weird behaviour? Can you verify the files aren't in the folder, and that the scan picks up and rescans all the games that are there?

**Comment by jcsomerville** [comment]
They for sure aren't in the folder anymore.

Earlier I hadn't thought to download one and when I do, in my browser, I get "Internal Server Error". I checked the logs and get the following.

```
05/18/2024
11:08:47 PM
Traceback (most recent call last):
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
05/18/2024
11:08:47 PM
    result = await app(  # type: ignore[func-returns-value]
05/18/2024
11:08:47 PM
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
05/18/2024
11:08:47 PM
    return await self.app(scope, receive, send)
05/18/2024
11:08:47 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
05/18/2024
11:08:47 PM
    await super().__call__(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
05/18/2024
11:08:47 PM
    await self.middleware_stack(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
05/18/2024
11:08:47 PM
    raise exc
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
05/18/2024
11:08:47 PM
    await self.app(scope, receive, _send)
05/18/2024
11:08:47 PM
  File "/backend/handler/auth/middleware.py", line 137, in __call__
05/18/2024
11:08:47 PM
    await self.app(scope, receive, send_wrapper)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/middleware/authentication.py", line 48, in __call__
05/18/2024
11:08:47 PM
    await self.app(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/handler/auth/middleware.py", line 18, in __call__
05/18/2024
11:08:47 PM
    await super().__call__(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette_csrf/middleware.py", line 72, in __call__
05/18/2024
11:08:47 PM
    await self.app(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
05/18/2024
11:08:47 PM
    await self.app(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
05/18/2024
11:08:47 PM
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
05/18/2024
11:08:47 PM
    raise exc
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
05/18/2024
11:08:47 PM
    await app(scope, receive, sender)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
05/18/2024
11:08:47 PM
    await self.middleware_stack(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
05/18/2024
11:08:47 PM
    await route.handle(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
05/18/2024
11:08:47 PM
    await self.app(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
05/18/2024
11:08:47 PM
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
05/18/2024
11:08:47 PM
    raise exc
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
05/18/2024
11:08:47 PM
    await app(scope, receive, sender)
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
05/18/2024
11:08:47 PM
    response = await func(request)
05/18/2024
11:08:47 PM
               ^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
05/18/2024
11:08:47 PM
    raw_response = await run_endpoint_function(
05/18/2024
11:08:47 PM
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
05/18/2024
11:08:47 PM
    return await run_in_threadpool(dependant.call, **values)
05/18/2024
11:08:47 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
05/18/2024
11:08:47 PM
    return await anyio.to_thread.run_sync(func, *args)
05/18/2024
11:08:47 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
05/18/2024
11:08:47 PM
    return await get_async_backend().run_sync_in_worker_thread(
05/18/2024
11:08:47 PM
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
05/18/2024
11:08:47 PM
    return await future
05/18/2024
11:08:47 PM
           ^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 851, in run
05/18/2024
11:08:47 PM
    result = context.run(func, *args)
05/18/2024
11:08:47 PM
             ^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/lib/python3.11/site-packages/starlette/authentication.py", line 104, in sync_wrapper
05/18/2024
11:08:47 PM
    return func(*args, **kwargs)
05/18/2024
11:08:47 PM
           ^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/endpoints/rom.py", line 233, in get_rom_content
05/18/2024
11:08:47 PM
    zipped_chunks = stream_zip(local_files())
05/18/2024
11:08:47 PM
                               ^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "/backend/endpoints/rom.py", line 214, in local_files
05/18/2024
11:08:47 PM
    return [
05/18/2024
11:08:47 PM
           ^
05/18/2024
11:08:47 PM
  File "/backend/endpoints/rom.py", line 219, in <listcomp>
05/18/2024
11:08:47 PM
    ZIP_AUTO(os.path.getsize(f"{rom_path}/{f}")),
05/18/2024
11:08:47 PM
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
05/18/2024
11:08:47 PM
  File "<frozen genericpath>", line 50, in getsize
05/18/2024
11:08:47 PM
FileNotFoundError: [Errno 2] No such file or directory: '/romm/library/PSX/roms/MediEvil II/MediEvil II (Track 1).bin'
```

**Comment by gantoine** [comment]
This error is from trying to download a file that doesn't exist anymore. So yeah it seems you have files RomM thinks are still there and tries to download them. If you run a quick scan on your PSX library from the scan page, what happens? And is this entire folder gone, `/PSX/roms/MediEvil II`?

**Comment by jcsomerville** [comment]
I no longer have any PSX folder at all. Just a few older systems remain. When running a quick scan on PSX it "found" the platform but no games.

Here are the logs.

```
5/19/2024
07:57:13 AM
INFO:	  [RomM][2024-05-19 11:57:13] 🔎 Scanning 
05/19/2024
07:57:13 AM
11:57:13 high: endpoints.sockets.scan.scan_platforms([14], <ScanType.QUICK: 'quick'>, [], ['igdb', 'moby']) (60e867b0-a7c7-43db-983e-e488eaa7d1d5)
05/19/2024
07:57:25 AM
INFO:	  [RomM][2024-05-19 11:57:25] Found 1 platforms in file system 
05/19/2024
07:57:25 AM
INFO:	  [RomM][2024-05-19 11:57:25] · PSX
05/19/2024
07:57:25 AM
WARNING:  [RomM][2024-05-19 11:57:25]   PSX not found in file system, trying to match via config...
05/19/2024
07:57:25 AM
INFO:	  [RomM][2024-05-19 11:57:25]   Identified as PlayStation 🎮
05/19/2024
07:57:25 AM
WARNING:  [RomM][2024-05-19 11:57:25]   ⚠️ No firmware found, skipping firmware scan for this platform
05/19/2024
07:57:25 AM
ERROR:	  [RomM][2024-05-19 11:57:25] Roms not found for platform PSX. Check RomM folder structure here: https://github.com/rommapp/romm?tab=readme-ov-file#folder-structure
05/19/2024
07:57:25 AM
INFO:	  [RomM][2024-05-19 11:57:25] ✔️  Scan completed 
```

**Comment by jcsomerville** [comment]
Actually I'm going to add on PSX game and see if it then recognizes there are no other games within that platform.

**Comment by gantoine** [comment]
> Should I create a new issue specific to that?

No need, I can reuse this issue. Fix for it is ready, thanks for debugging this!
