### ISSUE TITLE
[Bug] Unable to upload ROMS

### ISSUE THREAD

**Issue by groenator** [rommapp/romm#940]
**RomM version**
Latest Version 

**Describe the bug**
I am trying to upload a 3DO romm using firefox. Every time I upload the rom I am getting an error 500, that the file is not there. 

**To Reproduce**
1. Go to 'Rom manager app'
2. Click on 'On 3DO library and then click on upload rom'
4. See error in the docker logs that the file is not uploaded and couldn't be found.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OpenSuse
 - Browser Firefox
 - Version 1.26.01

**Smartphone (please complete the following information):**

**Additional context**

Logs:
```
  INFO:	  [RomM][2024-06-20 09:32:12]  - Uploading Crayon Shin-chan - Puzzle Daimaou no Nazo.zip
 - "POST /roms?platform_id=25 HTTP/1.0" 500
[2024-06-20 09:32:12 +0000] [24] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/backend/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/backend/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/backend/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/backend/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/backend/handler/auth/middleware.py", line 137, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/backend/lib/python3.11/site-packages/starlette/middleware/authentication.py", line 48, in __call__
    await self.app(scope, receive, send)
  File "/backend/handler/auth/middleware.py", line 18, in __call__
    await super().__call__(scope, receive, send)
  File "/backend/lib/python3.11/site-packages/starlette_csrf/middleware.py", line 72, in __call__
    await self.app(scope, receive, send)
  File "/backend/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/backend/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/backend/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/backend/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/backend/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/backend/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/starlette/concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/backend/lib/python3.11/site-packages/starlette/authentication.py", line 104, in sync_wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/backend/endpoints/rom.py", line 71, in add_roms
    with open(file_location, "wb+") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/romm/library/3do/roms/Crayon Shin-chan - Puzzle Daimaou no Nazo.zip'
INFO:	  [nginx][2024-06-20 09:32:12]	192.168.1.4 - - "POST /api/roms?platform_id=25 HTTP/1.1" 500 21 "https://romms.com/platform/25" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0" rt=4.046 uct="0.000" uht="1.507" urt="1.507"
```

**Comment by groenator** [comment]
I tried on Brave and Firefox. Same behaviour, the file cannot be found.

**Comment by gantoine** [comment]
@groenator Is this the first game you're trying to upload for 3do?

**Comment by groenator** [comment]
That's a very good question. I have another 3do game. I believe I uploaded the game onto the NAS and then scan the library. 
What it is odd with this game is that even if I upload the game on my NAS and then scan the library the game is not found. 

Should I try other 3do games?

**Comment by groenator** [comment]
I tried uploading another romm. I am getting error 500 straight away.

**Comment by gantoine** [comment]
So I created a file named `Crayon Shin-chan - Puzzle Daimaou no Nazo.zip`, uploaded it, and after a quick scan it showed up. Is it possible `/romm/library/3do/roms` doesn't exist, or that romm has no perms to write to it?

**Comment by groenator** [comment]
Hi, 

My set up is as follow: `library\roms\platform`. I followed the same folder structure as in your documentation. However, I believe this might not be the issue, the 3do folder is inside the library. It worked fine when I uploaded the first games. I did notice all the folders and files are owned by my local user 1002. Could this be an issue? Do I need to set the permissions to root user? I don't like using root for my containers, can I set my own PGID and PUID?

Regards,

**Comment by groenator** [comment]
I changed the permissions of my library folder to root, same issue. I am getting an error 500. I am going to do a clean install and try it out again.

**Comment by groenator** [comment]
I changed the permissions of my library folder to root, same issue. I am getting an error 500. I am going to do a clean install and try it out again.

**Comment by gantoine** [comment]
> I followed the same folder structure as in your documentation

folder structure B is supported 👍🏼 

> I did notice all the folders and files are owned by my local user 1002

That shouldn't be a problem, I use a custom user 1001 my my media

> I don't like using root for my containers, can I set my own PGID and PUID

PUID/PGID are not docker standards (they're only used by Linuxserver images), but you can try setting `user: 1002:1002` in your compose.

**Comment by groenator** [comment]
Hi, 

I appreciate your help. I manage to fix the issue by reinstalling everything from scratch. Everything works as expected. I used to have Roms in the library which weren't recognised before, now the roms are showing in the library. 

I am going to close this issue.
